[package]
name = "s3-bamheader"
version = "0.2.0"
authors = ["Roman Valls Guimera <brainstorm@nopcode.org>"]
edition = "2018"

[dependencies]
bytes = "1.0.1"
jemallocator = "0.3.0"
url = "2.1.1"
serde = "^1"
serde_derive = "^1"
serde_json = "^1"
lambda_runtime = { version = 0.3.1 }
aws-sdk-s3 = { git = "https://github.com/awslabs/aws-sdk-rust", tag = "v0.0.14-alpha" }
tracing-subscriber = "0.2.18"

tokio = { version = "1.7.1" }
noodles-bam = { git = "https://github.com/zaeleus/noodles" }
noodles-sam = { git = "https://github.com/zaeleus/noodles" }

[dev-dependencies]
s3-server = "0.0.1"

[[ bin ]]
name = "bootstrap"
path = "src/main.rs"

#[profile.release]
#lto = true
#opt-level = 'z'
#codegen-units = 1
