Resources:
  htsgetAws:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: s3-bamheader
      Handler: s3_read_bam_header
      Runtime: provided.al2
      MemorySize: 128
      Timeout: 30
      CodeUri: .
      Environment:
        Variables:
          CURL_CA_BUNDLE: cert.pem
# In case you wanted to run API Gateway...
      Events:
        testEvent:
          Type: Api
          Properties:
            Path: /reads/{proxy+}
            Method: get
    Metadata:
      BuildMethod: makefile
