Resources:
  htsgetAws:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: htsget-aws
      Handler: foo
      Runtime: provided
      MemorySize: 128
      CodeUri: .
      Environment:
        Variables:
          CURL_CA_BUNDLE: cert.pem
    Metadata:
      BuildMethod: makefile
