AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  s3Bam:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: s3Bam
      Handler: bootstrap
      Runtime: provided.al2
      MemorySize: 128
      Architectures: ["arm64"]
      Timeout: 30
      CodeUri: .
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
      Tags:
        "Creator": "brainstorm"
        "Deploy": "sam"
      Environment:
        Variables:
          BUCKET: "umccr-research-dev"
          KEY: "htsget/htsnexus_test_NA12878.bam"
      Events:
        RootEvent:
          Type: Api
          Properties:
            Path: /
            Method: any
        GatewayEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
