Transform: AWS::Serverless-2016-10-31
Resources:
  s3Bam:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: s3Bam
      Handler: bootstrap.is.real.handler
      Runtime: provided.al2
      MemorySize: 128
      Architectures: ["x86_64"]
      Timeout: 30
      CodeUri: .
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonS3ReadOnlyAccess
      Tags:
        "Creator": "brainstorm"
        "Deploy": "sam"
      Events:
        RootEvent:
          Type: Api
          Properties:
            Path: /
            Method: any
        GatewayEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
